# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: meshtastic/protobuf/tracker.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'meshtastic/protobuf/tracker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!meshtastic/protobuf/tracker.proto\x12\x13meshtastic.protobuf\"\xcd\x02\n\x07Tracker\x12\x11\n\tcall_sign\x18\x01 \x01(\t\x12\x0c\n\x04ssid\x18\x02 \x01(\r\x12\x12\n\nlatitude_i\x18\x03 \x01(\x0f\x12\x13\n\x0blongitude_i\x18\x04 \x01(\x0f\x12\x10\n\x08\x61ltitude\x18\x05 \x01(\x05\x12\x11\n\ttimestamp\x18\x06 \x01(\x07\x12\x14\n\x0cground_speed\x18\x07 \x01(\r\x12\x14\n\x0cground_track\x18\x08 \x01(\r\x12\x14\n\x0csats_in_view\x18\t \x01(\r\x12\x16\n\x0eprecision_bits\x18\n \x01(\r\x12\x13\n\x0btemperature\x18\x0b \x01(\x02\x12\x19\n\x11relative_humidity\x18\x0c \x01(\x02\x12\x1b\n\x13\x62\x61rometric_pressure\x18\r \x01(\x02\x12\x0f\n\x07voltage\x18\x0e \x01(\x02\x12\x1b\n\x13\x63hannel_utilization\x18\x0f \x01(\x02\x42\x62\n\x13\x63om.geeksville.meshB\rTrackerProtosZ\"github.com/meshtastic/go/generated\xaa\x02\x14Meshtastic.Protobufs\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'meshtastic.protobuf.tracker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.geeksville.meshB\rTrackerProtosZ\"github.com/meshtastic/go/generated\252\002\024Meshtastic.Protobufs\272\002\000'
  _globals['_TRACKER']._serialized_start=59
  _globals['_TRACKER']._serialized_end=392
# @@protoc_insertion_point(module_scope)
