"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Tracker(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CALL_SIGN_FIELD_NUMBER: builtins.int
    SSID_FIELD_NUMBER: builtins.int
    LATITUDE_I_FIELD_NUMBER: builtins.int
    LONGITUDE_I_FIELD_NUMBER: builtins.int
    ALTITUDE_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    GROUND_SPEED_FIELD_NUMBER: builtins.int
    GROUND_TRACK_FIELD_NUMBER: builtins.int
    SATS_IN_VIEW_FIELD_NUMBER: builtins.int
    PRECISION_BITS_FIELD_NUMBER: builtins.int
    TEMPERATURE_FIELD_NUMBER: builtins.int
    RELATIVE_HUMIDITY_FIELD_NUMBER: builtins.int
    BAROMETRIC_PRESSURE_FIELD_NUMBER: builtins.int
    VOLTAGE_FIELD_NUMBER: builtins.int
    CHANNEL_UTILIZATION_FIELD_NUMBER: builtins.int
    call_sign: builtins.str
    ssid: builtins.int
    latitude_i: builtins.int
    longitude_i: builtins.int
    altitude: builtins.int
    timestamp: builtins.int
    ground_speed: builtins.int
    ground_track: builtins.int
    sats_in_view: builtins.int
    precision_bits: builtins.int
    temperature: builtins.float
    relative_humidity: builtins.float
    barometric_pressure: builtins.float
    voltage: builtins.float
    channel_utilization: builtins.float
    def __init__(
        self,
        *,
        call_sign: builtins.str = ...,
        ssid: builtins.int = ...,
        latitude_i: builtins.int = ...,
        longitude_i: builtins.int = ...,
        altitude: builtins.int = ...,
        timestamp: builtins.int = ...,
        ground_speed: builtins.int = ...,
        ground_track: builtins.int = ...,
        sats_in_view: builtins.int = ...,
        precision_bits: builtins.int = ...,
        temperature: builtins.float = ...,
        relative_humidity: builtins.float = ...,
        barometric_pressure: builtins.float = ...,
        voltage: builtins.float = ...,
        channel_utilization: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["altitude", b"altitude", "barometric_pressure", b"barometric_pressure", "call_sign", b"call_sign", "channel_utilization", b"channel_utilization", "ground_speed", b"ground_speed", "ground_track", b"ground_track", "latitude_i", b"latitude_i", "longitude_i", b"longitude_i", "precision_bits", b"precision_bits", "relative_humidity", b"relative_humidity", "sats_in_view", b"sats_in_view", "ssid", b"ssid", "temperature", b"temperature", "timestamp", b"timestamp", "voltage", b"voltage"]) -> None: ...

global___Tracker = Tracker
